sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
#  - wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -O /tmp/chromedriver
#  - chmod 777 /tmp/chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - python setup.py develop
#env:
#  - CHROME_DRIVER_PATH=/tmp/chromedriver
   - CHROME_DRIVER_PATH=/usr/lib/chromium-browser/chromedriver
script: pytest
